# Generated by Django 4.2.1 on 2023-05-29 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='orderedmeals',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
